### ISSUE TITLE
Integrate iModel/project picker

### ISSUE THREAD

**Issue by dsmailys** [imodeljs/create-react-app#77]
### Is your proposal related to a problem?

Not a problem/bug in particular, but electron template app has iModel/project picker integrated while web app template does not.

### Describe the solution you'd like

I think it would be helpful to instead of using .env file to set iModel specific configuration we could reuse an iModel picker widget from the getgo.

### Describe alternatives you've considered

Implementing this ourselves.

**Comment by aruniverse** [comment]
Well you'd still have the .env file for needing to enter auth credentials. And since we have multiple examples of using the project / iModel pickers (desktop viewer template / demo portal) I don't think we will pick this up anytime soon. 

Also, this enhancement / feature request has nothing to do with CRA.

**Comment by calebmshafer** [comment]
@dsmailys going to transfer this to the iTwin viewer repo. As @aruniverse says, we kept the web template a lot slimmer than the desktop one due to people having many different ways of wants to configure the viewer in the web (i.e. iframe, small portion of larger portal, etc.). This way it gives the basic setup and then allows you to build from there.

The iModel/project picker is available [here](https://github.com/iTwin/admin-components-react/tree/main/packages/modules/imodel-browser) and here's the link to the [demo portal](https://github.com/itwin/demo-portal).

**Comment by dsmailys** [comment]
Thanks for the explanation guys and it makes sense. Let's close out the issue then.
